# Базовое изображение с Node.js (LTS версия)
FROM node:18

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json из папки frontend-app
COPY frontend/package.json frontend/package-lock.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем все файлы проекта из папки frontend-app в контейнер
COPY frontend/ ./

# Устанавливаем переменную окружения для разработки
ENV NODE_ENV=development

# Пробрасываем порт, который использует Next.js (по умолчанию 3000)
EXPOSE 3000

# Запускаем приложение в режиме разработки
CMD ["npm", "run", "dev"]
