# Используем Python 3.11 в качестве базового образа
FROM python:3.11-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файл зависимостей и устанавливаем их
COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Копируем все файлы в контейнер
COPY backend/ ./

# Запускаем создание таблиц и приложение
CMD ["sh", "-c", "python3 database/create_tables.py && uvicorn main:app --host 0.0.0.0 --port 8000"]
